### PR TITLE
skip failing proxy test for upstream

### PR DESCRIPTION
**Pull request by soyacz**
After switching scylla address ip range to 127.0.%d. `TestDiscoverViaProxy` fails.

Disabled this test for upstream before it is fixed. Raised an issue for fixing: https://github.com/scylladb/gocql/issues/146

### CODE REVIEW

**Comment by fruch** [comment]
@soyacz we don't have a way to skip via the matrix code ? i.e. from command line or such ? handling it via patches gonna be painful on the long run

**Comment by fruch** [comment]
> @soyacz we don't have a way to skip via the matrix code ? i.e. from command line or such ? handling it via patches gonna be painful on the long run

I would open an issue of having that

looks like recently go got such a feature:
https://github.com/golang/go/commit/e4a2c38af5bdae12591004c3d35762d23da7a9bd

**Comment by soyacz** [comment]
> > @soyacz we don't have a way to skip via the matrix code ? i.e. from command line or such ? handling it via patches gonna be painful on the long run
> 
> I would open an issue of having that
> 
> looks like recently go got such a feature: [golang/go@e4a2c38](https://github.com/golang/go/commit/e4a2c38af5bdae12591004c3d35762d23da7a9bd)

I was looking in the past, but resigned after seeing some post it is not supported...
I just verified manually, it works. I'll change this PR with this approach.

**Review by fruch — APPROVED** [review]
LGTM

**Comment by soyacz** [comment]
I tested it here: https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/gocql-driver-matrix/25/
anyway, it's merged ;)

**Pull request merged**
